FROM mcr.microsoft.com/playwright:python-3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bot.py .
COPY clients_data.json .

CMD ["python", "bot.py"]
